# coding: utf-8

"""
    management-api

    REST API documentation for the management-api

    The version of the OpenAPI document: 4.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.contract_definition_v3_api import ContractDefinitionV3Api


class TestContractDefinitionV3Api(unittest.TestCase):
    """ContractDefinitionV3Api unit test stubs"""

    def setUp(self) -> None:
        self.api = ContractDefinitionV3Api()

    def tearDown(self) -> None:
        pass

    def test_create_contract_definition_v3(self) -> None:
        """Test case for create_contract_definition_v3

        """
        pass

    def test_delete_contract_definition_v3(self) -> None:
        """Test case for delete_contract_definition_v3

        """
        pass

    def test_get_contract_definition_v3(self) -> None:
        """Test case for get_contract_definition_v3

        """
        pass

    def test_query_contract_definitions_v3(self) -> None:
        """Test case for query_contract_definitions_v3

        """
        pass

    def test_update_contract_definition_v3(self) -> None:
        """Test case for update_contract_definition_v3

        """
        pass


if __name__ == '__main__':
    unittest.main()
