# coding: utf-8

"""
    management-api

    REST API documentation for the management-api

    The version of the OpenAPI document: 4.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.permission_step import PermissionStep

class TestPermissionStep(unittest.TestCase):
    """PermissionStep unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PermissionStep:
        """Test PermissionStep
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PermissionStep`
        """
        model = PermissionStep()
        if include_optional:
            return PermissionStep(
                is_filtered = True,
                filtering_reasons = [
                    ''
                    ],
                constraint_steps = [
                    null
                    ],
                rule_functions = [
                    ''
                    ],
                type = '',
                duty_steps = [
                    {"ruleFunctions":["ruleFunctions","ruleFunctions"],"filteringReasons":["filteringReasons","filteringReasons"],"@type":"@type","isFiltered":true,"constraintSteps":[null,null]}
                    ]
            )
        else:
            return PermissionStep(
                type = '',
        )
        """

    def testPermissionStep(self):
        """Test PermissionStep"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
