# coding: utf-8

"""
    management-api

    REST API documentation for the management-api

    The version of the OpenAPI document: 4.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.or_constraint_step import OrConstraintStep

class TestOrConstraintStep(unittest.TestCase):
    """OrConstraintStep unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OrConstraintStep:
        """Test OrConstraintStep
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OrConstraintStep`
        """
        model = OrConstraintStep()
        if include_optional:
            return OrConstraintStep(
                constraint_steps = [
                    null
                    ],
                type = ''
            )
        else:
            return OrConstraintStep(
                constraint_steps = [
                    null
                    ],
                type = '',
        )
        """

    def testOrConstraintStep(self):
        """Test OrConstraintStep"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
