# coding: utf-8

"""
    management-api

    REST API documentation for the management-api

    The version of the OpenAPI document: 4.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.terminate_negotiation_v3 import TerminateNegotiationV3

class TestTerminateNegotiationV3(unittest.TestCase):
    """TerminateNegotiationV3 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TerminateNegotiationV3:
        """Test TerminateNegotiationV3
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TerminateNegotiationV3`
        """
        model = TerminateNegotiationV3()
        if include_optional:
            return TerminateNegotiationV3(
                id = '',
                type = 'https://w3id.org/edc/v0.0.1/ns/TerminateNegotiation',
                reason = ''
            )
        else:
            return TerminateNegotiationV3(
        )
        """

    def testTerminateNegotiationV3(self):
        """Test TerminateNegotiationV3"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
