# coding: utf-8

"""
    management-api

    REST API documentation for the management-api

    The version of the OpenAPI document: 4.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.multiplicity_constraint_step import MultiplicityConstraintStep

class TestMultiplicityConstraintStep(unittest.TestCase):
    """MultiplicityConstraintStep unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MultiplicityConstraintStep:
        """Test MultiplicityConstraintStep
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MultiplicityConstraintStep`
        """
        model = MultiplicityConstraintStep()
        if include_optional:
            return MultiplicityConstraintStep(
                constraint_steps = [
                    null
                    ]
            )
        else:
            return MultiplicityConstraintStep(
                constraint_steps = [
                    null
                    ],
        )
        """

    def testMultiplicityConstraintStep(self):
        """Test MultiplicityConstraintStep"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
