# coding: utf-8

"""
    management-api

    REST API documentation for the management-api

    The version of the OpenAPI document: 4.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from edc_client.models.discovery_response_schema import DiscoveryResponseSchema

class TestDiscoveryResponseSchema(unittest.TestCase):
    """DiscoveryResponseSchema unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DiscoveryResponseSchema:
        """Test DiscoveryResponseSchema
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DiscoveryResponseSchema`
        """
        model = DiscoveryResponseSchema()
        if include_optional:
            return DiscoveryResponseSchema(
                context = [
                    ''
                    ],
                type = '',
                profile = '',
                version = '',
                counter_party = {"path":"path","dataServiceEndpoint":"dataServiceEndpoint"},
                binding = ''
            )
        else:
            return DiscoveryResponseSchema(
                type = '',
                profile = '',
                version = '',
                counter_party = {"path":"path","dataServiceEndpoint":"dataServiceEndpoint"},
                binding = '',
        )
        """

    def testDiscoveryResponseSchema(self):
        """Test DiscoveryResponseSchema"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
