# coding: utf-8

"""
    management-api

    REST API documentation for the management-api

    The version of the OpenAPI document: 4.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.catalogs_v4_api import CatalogsV4Api


class TestCatalogsV4Api(unittest.TestCase):
    """CatalogsV4Api unit test stubs"""

    def setUp(self) -> None:
        self.api = CatalogsV4Api()

    def tearDown(self) -> None:
        pass

    def test_request_catalogs_v4(self) -> None:
        """Test case for request_catalogs_v4

        """
        pass


if __name__ == '__main__':
    unittest.main()
