# coding: utf-8

"""
    management-api

    REST API documentation for the management-api

    The version of the OpenAPI document: 4.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from edc_client.models.callback_address1 import CallbackAddress1

class TestCallbackAddress1(unittest.TestCase):
    """CallbackAddress1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CallbackAddress1:
        """Test CallbackAddress1
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CallbackAddress1`
        """
        model = CallbackAddress1()
        if include_optional:
            return CallbackAddress1(
                type = 'https://w3id.org/edc/v0.0.1/ns/CallbackAddress',
                auth_code_id = '',
                auth_key = '',
                events = [
                    ''
                    ],
                transactional = True,
                uri = ''
            )
        else:
            return CallbackAddress1(
        )
        """

    def testCallbackAddress1(self):
        """Test CallbackAddress1"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
