# coding: utf-8

"""
    management-api

    REST API documentation for the management-api

    The version of the OpenAPI document: 4.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.offer_v3 import OfferV3

class TestOfferV3(unittest.TestCase):
    """OfferV3 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OfferV3:
        """Test OfferV3
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OfferV3`
        """
        model = OfferV3()
        if include_optional:
            return OfferV3(
                id = '',
                type = 'http://www.w3.org/ns/odrl/2/Offer',
                assigner = '',
                target = ''
            )
        else:
            return OfferV3(
                id = '',
                assigner = '',
                target = '',
        )
        """

    def testOfferV3(self):
        """Test OfferV3"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
