# coding: utf-8

"""
    management-api

    REST API documentation for the management-api

    The version of the OpenAPI document: 4.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from edc_client.models.query_spec9 import QuerySpec9

class TestQuerySpec9(unittest.TestCase):
    """QuerySpec9 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> QuerySpec9:
        """Test QuerySpec9
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `QuerySpec9`
        """
        model = QuerySpec9()
        if include_optional:
            return QuerySpec9(
                context = None,
                type = 'https://w3id.org/edc/v0.0.1/ns/QuerySpec',
                filter_expression = [
                    {"@context":{"@vocab":"https://w3id.org/edc/v0.0.1/ns/"},"@type":"Criterion","operandLeft":"fieldName","operator":"=","operandRight":"some value"}
                    ],
                limit = 56,
                offset = 56,
                sort_field = '',
                sort_order = 'ASC'
            )
        else:
            return QuerySpec9(
        )
        """

    def testQuerySpec9(self):
        """Test QuerySpec9"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
