# coding: utf-8

"""
    management-api

    REST API documentation for the management-api

    The version of the OpenAPI document: 4.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.policy_definition_input_v3 import PolicyDefinitionInputV3

class TestPolicyDefinitionInputV3(unittest.TestCase):
    """PolicyDefinitionInputV3 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PolicyDefinitionInputV3:
        """Test PolicyDefinitionInputV3
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PolicyDefinitionInputV3`
        """
        model = PolicyDefinitionInputV3()
        if include_optional:
            return PolicyDefinitionInputV3(
                context = None,
                id = '',
                type = 'https://w3id.org/edc/v0.0.1/ns/PolicyDefinition',
                policy = {"@context":"http://www.w3.org/ns/odrl.jsonld","@id":"0949ba30-680c-44e6-bc7d-1688cbe1847e","@type":"odrl:Set","permission":{"target":"http://example.com/asset:9898.movie","action":{"type":"http://www.w3.org/ns/odrl/2/use"},"constraint":{"leftOperand":"https://w3id.org/edc/v0.0.1/ns/left","operator":"eq","rightOperand":"value"}},"prohibition":[],"obligation":[]}
            )
        else:
            return PolicyDefinitionInputV3(
                context = None,
                policy = {"@context":"http://www.w3.org/ns/odrl.jsonld","@id":"0949ba30-680c-44e6-bc7d-1688cbe1847e","@type":"odrl:Set","permission":{"target":"http://example.com/asset:9898.movie","action":{"type":"http://www.w3.org/ns/odrl/2/use"},"constraint":{"leftOperand":"https://w3id.org/edc/v0.0.1/ns/left","operator":"eq","rightOperand":"value"}},"prohibition":[],"obligation":[]},
        )
        """

    def testPolicyDefinitionInputV3(self):
        """Test PolicyDefinitionInputV3"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
