# coding: utf-8

"""
    management-api

    REST API documentation for the management-api

    The version of the OpenAPI document: 4.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from edc_client.models.contract_negotiation_schema import ContractNegotiationSchema

class TestContractNegotiationSchema(unittest.TestCase):
    """ContractNegotiationSchema unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ContractNegotiationSchema:
        """Test ContractNegotiationSchema
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ContractNegotiationSchema`
        """
        model = ContractNegotiationSchema()
        if include_optional:
            return ContractNegotiationSchema(
                context = [
                    ''
                    ],
                type = '',
                id = '',
                type = 'CONSUMER',
                state = '',
                state_timestamp = 56,
                protocol = '',
                profile = '',
                created_at = 56,
                callback_addresses = [
                    {"authKey":"authKey","@type":"@type","authCodeId":"authCodeId","uri":"uri","transactional":true,"events":["events","events"]}
                    ],
                counter_party_address = '',
                counter_party_id = '',
                error_detail = '',
                correlation_id = '',
                asset_id = '',
                contract_agreement_id = ''
            )
        else:
            return ContractNegotiationSchema(
                context = [
                    ''
                    ],
                type = '',
                id = '',
                type = 'CONSUMER',
                state = '',
                protocol = '',
                profile = '',
                created_at = 56,
                counter_party_address = '',
                counter_party_id = '',
        )
        """

    def testContractNegotiationSchema(self):
        """Test ContractNegotiationSchema"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
