# coding: utf-8

"""
    management-api

    REST API documentation for the management-api

    The version of the OpenAPI document: 4.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.offer import Offer

class TestOffer(unittest.TestCase):
    """Offer unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Offer:
        """Test Offer
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Offer`
        """
        model = Offer()
        if include_optional:
            return Offer(
                id = '',
                profile = None,
                permission = [
                    {"action":"action","constraint":[{"or":[null,null],"andSequence":[null,null],"and":[null,null],"xone":[null,null]},{"or":[null,null],"andSequence":[null,null],"and":[null,null],"xone":[null,null]}]}
                    ],
                prohibition = [
                    {"action":"action","constraint":[null,null]}
                    ],
                obligation = [
                    {"action":null,"constraint":[null,null]}
                    ],
                type = ''
            )
        else:
            return Offer(
                id = '',
        )
        """

    def testOffer(self):
        """Test Offer"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
