# coding: utf-8

"""
    management-api

    REST API documentation for the management-api

    The version of the OpenAPI document: 4.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from edc_client.api.edr_cache_v3_api import EDRCacheV3Api


class TestEDRCacheV3Api(unittest.TestCase):
    """EDRCacheV3Api unit test stubs"""

    def setUp(self) -> None:
        self.api = EDRCacheV3Api()

    def tearDown(self) -> None:
        pass

    def test_get_edr_entry_data_address_v3(self) -> None:
        """Test case for get_edr_entry_data_address_v3

        """
        pass

    def test_remove_edr_entry_v3(self) -> None:
        """Test case for remove_edr_entry_v3

        """
        pass

    def test_request_edr_entries_v3(self) -> None:
        """Test case for request_edr_entries_v3

        """
        pass


if __name__ == '__main__':
    unittest.main()
