# coding: utf-8

"""
    management-api

    REST API documentation for the management-api

    The version of the OpenAPI document: 4.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from edc_client.api.participant_context_config_v5beta_api import ParticipantContextConfigV5betaApi


class TestParticipantContextConfigV5betaApi(unittest.TestCase):
    """ParticipantContextConfigV5betaApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ParticipantContextConfigV5betaApi()

    def tearDown(self) -> None:
        pass

    def test_get_config_v5(self) -> None:
        """Test case for get_config_v5

        """
        pass

    def test_set_config_v5(self) -> None:
        """Test case for set_config_v5

        """
        pass


if __name__ == '__main__':
    unittest.main()
