# coding: utf-8

"""
    management-api

    REST API documentation for the management-api

    The version of the OpenAPI document: 4.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from edc_client.models.transfer_process_v3 import TransferProcessV3

class TestTransferProcessV3(unittest.TestCase):
    """TransferProcessV3 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TransferProcessV3:
        """Test TransferProcessV3
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TransferProcessV3`
        """
        model = TransferProcessV3()
        if include_optional:
            return TransferProcessV3(
                id = '',
                type = 'https://w3id.org/edc/v0.0.1/ns/TransferProcess',
                callback_addresses = [
                    edc_client.models.callback_address_1.CallbackAddress_1(
                        @type = 'https://w3id.org/edc/v0.0.1/ns/CallbackAddress', 
                        auth_code_id = '', 
                        auth_key = '', 
                        events = [
                            ''
                            ], 
                        transactional = True, 
                        uri = '', )
                    ],
                contract_agreement_id = '',
                counter_party_address = '',
                counter_party_id = '',
                data_destination = {"@type":"https://w3id.org/edc/v0.0.1/ns/DataAddress","type":"type"},
                error_detail = '',
                private_properties = { },
                protocol = '',
                state = '',
                type = 'CONSUMER'
            )
        else:
            return TransferProcessV3(
        )
        """

    def testTransferProcessV3(self):
        """Test TransferProcessV3"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
