# coding: utf-8

"""
    management-api

    REST API documentation for the management-api

    The version of the OpenAPI document: 4.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from edc_client.models.transfer_request_v3 import TransferRequestV3

class TestTransferRequestV3(unittest.TestCase):
    """TransferRequestV3 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TransferRequestV3:
        """Test TransferRequestV3
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TransferRequestV3`
        """
        model = TransferRequestV3()
        if include_optional:
            return TransferRequestV3(
                context = None,
                type = 'https://w3id.org/edc/v0.0.1/ns/TransferRequest',
                asset_id = '',
                callback_addresses = [
                    edc_client.models.callback_address_1.CallbackAddress_1(
                        @type = 'https://w3id.org/edc/v0.0.1/ns/CallbackAddress', 
                        auth_code_id = '', 
                        auth_key = '', 
                        events = [
                            ''
                            ], 
                        transactional = True, 
                        uri = '', )
                    ],
                contract_id = '',
                counter_party_address = '',
                data_destination = {"@type":"https://w3id.org/edc/v0.0.1/ns/DataAddress","type":"type"},
                private_properties = { },
                protocol = '',
                transfer_type = ''
            )
        else:
            return TransferRequestV3(
                context = None,
                contract_id = '',
                counter_party_address = '',
                protocol = '',
                transfer_type = '',
        )
        """

    def testTransferRequestV3(self):
        """Test TransferRequestV3"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
