# coding: utf-8

"""
    management-api

    REST API documentation for the management-api

    The version of the OpenAPI document: 4.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.policy_definition import PolicyDefinition

class TestPolicyDefinition(unittest.TestCase):
    """PolicyDefinition unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PolicyDefinition:
        """Test PolicyDefinition
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PolicyDefinition`
        """
        model = PolicyDefinition()
        if include_optional:
            return PolicyDefinition(
                context = [
                    ''
                    ],
                type = '',
                id = '',
                policy = {"@type":"@type","obligation":[{"action":null,"constraint":[null,null]},{"action":null,"constraint":[null,null]}],"profile":["PolicyClass_profile","PolicyClass_profile"],"prohibition":[{"action":"action","constraint":[null,null]},{"action":"action","constraint":[null,null]}],"permission":[{"action":"action","constraint":[{"or":[null,null],"andSequence":[null,null],"and":[null,null],"xone":[null,null]},{"or":[null,null],"andSequence":[null,null],"and":[null,null],"xone":[null,null]}]},{"action":"action","constraint":[{"or":[null,null],"andSequence":[null,null],"and":[null,null],"xone":[null,null]},{"or":[null,null],"andSequence":[null,null],"and":[null,null],"xone":[null,null]}]}]},
                private_properties = {"privateKey":"privateValue"}
            )
        else:
            return PolicyDefinition(
                context = [
                    ''
                    ],
                type = '',
                policy = {"@type":"@type","obligation":[{"action":null,"constraint":[null,null]},{"action":null,"constraint":[null,null]}],"profile":["PolicyClass_profile","PolicyClass_profile"],"prohibition":[{"action":"action","constraint":[null,null]},{"action":"action","constraint":[null,null]}],"permission":[{"action":"action","constraint":[{"or":[null,null],"andSequence":[null,null],"and":[null,null],"xone":[null,null]},{"or":[null,null],"andSequence":[null,null],"and":[null,null],"xone":[null,null]}]},{"action":"action","constraint":[{"or":[null,null],"andSequence":[null,null],"and":[null,null],"xone":[null,null]},{"or":[null,null],"andSequence":[null,null],"and":[null,null],"xone":[null,null]}]}]},
        )
        """

    def testPolicyDefinition(self):
        """Test PolicyDefinition"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
