# coding: utf-8

"""
    management-api

    REST API documentation for the management-api

    The version of the OpenAPI document: 4.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from edc_client.models.participant_context import ParticipantContext

class TestParticipantContext(unittest.TestCase):
    """ParticipantContext unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ParticipantContext:
        """Test ParticipantContext
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ParticipantContext`
        """
        model = ParticipantContext()
        if include_optional:
            return ParticipantContext(
                context = [
                    ''
                    ],
                type = '',
                id = '',
                identity = '',
                properties = edc_client.models.properties.properties(),
                state = 'CREATED'
            )
        else:
            return ParticipantContext(
                context = [
                    ''
                    ],
                type = '',
                identity = '',
        )
        """

    def testParticipantContext(self):
        """Test ParticipantContext"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
