# coding: utf-8

"""
    management-api

    REST API documentation for the management-api

    The version of the OpenAPI document: 4.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from edc_client.models.data_service import DataService

class TestDataService(unittest.TestCase):
    """DataService unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DataService:
        """Test DataService
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DataService`
        """
        model = DataService()
        if include_optional:
            return DataService(
                id = '',
                type = '',
                endpoint_url = '',
                serves_dataset = [
                    edc_client.models.dataset.Dataset()
                    ]
            )
        else:
            return DataService(
                id = '',
                type = '',
                endpoint_url = '',
        )
        """

    def testDataService(self):
        """Test DataService"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
