# coding: utf-8

"""
    management-api

    REST API documentation for the management-api

    The version of the OpenAPI document: 4.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.asset_input_v3 import AssetInputV3

class TestAssetInputV3(unittest.TestCase):
    """AssetInputV3 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AssetInputV3:
        """Test AssetInputV3
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AssetInputV3`
        """
        model = AssetInputV3()
        if include_optional:
            return AssetInputV3(
                context = None,
                id = '',
                type = 'https://w3id.org/edc/v0.0.1/ns/Asset',
                data_address = {"@type":"https://w3id.org/edc/v0.0.1/ns/DataAddress","type":"type"},
                private_properties = { },
                properties = { }
            )
        else:
            return AssetInputV3(
                context = None,
                data_address = {"@type":"https://w3id.org/edc/v0.0.1/ns/DataAddress","type":"type"},
                properties = { },
        )
        """

    def testAssetInputV3(self):
        """Test AssetInputV3"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
