# coding: utf-8

"""
    management-api

    REST API documentation for the management-api

    The version of the OpenAPI document: 4.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.terminate_transfer_v3 import TerminateTransferV3

class TestTerminateTransferV3(unittest.TestCase):
    """TerminateTransferV3 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TerminateTransferV3:
        """Test TerminateTransferV3
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TerminateTransferV3`
        """
        model = TerminateTransferV3()
        if include_optional:
            return TerminateTransferV3(
                type = 'https://w3id.org/edc/v0.0.1/ns/TerminateTransfer',
                state = ''
            )
        else:
            return TerminateTransferV3(
        )
        """

    def testTerminateTransferV3(self):
        """Test TerminateTransferV3"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
