# coding: utf-8

"""
    management-api

    REST API documentation for the management-api

    The version of the OpenAPI document: 4.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.asset_v3_api import AssetV3Api


class TestAssetV3Api(unittest.TestCase):
    """AssetV3Api unit test stubs"""

    def setUp(self) -> None:
        self.api = AssetV3Api()

    def tearDown(self) -> None:
        pass

    def test_create_asset_v3(self) -> None:
        """Test case for create_asset_v3

        """
        pass

    def test_get_asset_v3(self) -> None:
        """Test case for get_asset_v3

        """
        pass

    def test_remove_asset_v3(self) -> None:
        """Test case for remove_asset_v3

        """
        pass

    def test_request_assets_v3(self) -> None:
        """Test case for request_assets_v3

        """
        pass

    def test_update_asset_v3(self) -> None:
        """Test case for update_asset_v3

        """
        pass


if __name__ == '__main__':
    unittest.main()
