# coding: utf-8

"""
    management-api

    REST API documentation for the management-api

    The version of the OpenAPI document: 4.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.transfer_request import TransferRequest

class TestTransferRequest(unittest.TestCase):
    """TransferRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TransferRequest:
        """Test TransferRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TransferRequest`
        """
        model = TransferRequest()
        if include_optional:
            return TransferRequest(
                context = [
                    ''
                    ],
                type = '',
                id = '',
                counter_party_address = '',
                protocol = '',
                profile = '',
                contract_id = '',
                transfer_type = '',
                private_properties = openapi_client.models.private_properties.privateProperties(),
                callback_addresses = [
                    {"authKey":"authKey","@type":"@type","authCodeId":"authCodeId","uri":"uri","transactional":true,"events":["events","events"]}
                    ],
                dataplane_metadata = {"@type":"@type","profiles":["profiles","profiles"],"properties":{"key":"value"},"labels":["labels","labels"]}
            )
        else:
            return TransferRequest(
                context = [
                    ''
                    ],
                type = '',
                counter_party_address = '',
                contract_id = '',
                transfer_type = '',
        )
        """

    def testTransferRequest(self):
        """Test TransferRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
