# coding: utf-8

"""
    management-api

    REST API documentation for the management-api

    The version of the OpenAPI document: 4.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.dataspace_profile_context_v5beta_api import DataspaceProfileContextV5betaApi


class TestDataspaceProfileContextV5betaApi(unittest.TestCase):
    """DataspaceProfileContextV5betaApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DataspaceProfileContextV5betaApi()

    def tearDown(self) -> None:
        pass

    def test_associate_profiles(self) -> None:
        """Test case for associate_profiles

        """
        pass

    def test_get_profiles_v5(self) -> None:
        """Test case for get_profiles_v5

        """
        pass


if __name__ == '__main__':
    unittest.main()
