# coding: utf-8

"""
    management-api

    REST API documentation for the management-api

    The version of the OpenAPI document: 4.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.catalog_request_v3 import CatalogRequestV3

class TestCatalogRequestV3(unittest.TestCase):
    """CatalogRequestV3 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CatalogRequestV3:
        """Test CatalogRequestV3
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CatalogRequestV3`
        """
        model = CatalogRequestV3()
        if include_optional:
            return CatalogRequestV3(
                context = None,
                type = 'https://w3id.org/edc/v0.0.1/ns/CatalogRequest',
                additional_scopes = [
                    ''
                    ],
                counter_party_address = '',
                counter_party_id = '',
                protocol = '',
                query_spec = {"@context":{"@vocab":"https://w3id.org/edc/v0.0.1/ns/"},"@type":"QuerySpec","offset":5,"limit":10,"sortOrder":"DESC","sortField":"fieldName","filterExpression":[]}
            )
        else:
            return CatalogRequestV3(
                context = None,
                counter_party_address = '',
                protocol = '',
        )
        """

    def testCatalogRequestV3(self):
        """Test CatalogRequestV3"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
