# coding: utf-8

"""
    management-api

    REST API documentation for the management-api

    The version of the OpenAPI document: 4.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from edc_client.models.data_plane_instance_schema_v4 import DataPlaneInstanceSchemaV4

class TestDataPlaneInstanceSchemaV4(unittest.TestCase):
    """DataPlaneInstanceSchemaV4 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DataPlaneInstanceSchemaV4:
        """Test DataPlaneInstanceSchemaV4
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DataPlaneInstanceSchemaV4`
        """
        model = DataPlaneInstanceSchemaV4()
        if include_optional:
            return DataPlaneInstanceSchemaV4(
                context = None,
                id = '',
                type = 'https://w3id.org/edc/v0.0.1/ns/DataPlaneInstance',
                allowed_source_types = [
                    ''
                    ],
                last_active = 56,
                state = '',
                state_timestamp = 56,
                url = ''
            )
        else:
            return DataPlaneInstanceSchemaV4(
                context = None,
                allowed_source_types = [
                    ''
                    ],
                url = '',
        )
        """

    def testDataPlaneInstanceSchemaV4(self):
        """Test DataPlaneInstanceSchemaV4"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
