# coding: utf-8

"""
    management-api

    REST API documentation for the management-api

    The version of the OpenAPI document: 4.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.catalog_v4_api import CatalogV4Api


class TestCatalogV4Api(unittest.TestCase):
    """CatalogV4Api unit test stubs"""

    def setUp(self) -> None:
        self.api = CatalogV4Api()

    def tearDown(self) -> None:
        pass

    def test_get_dataset_v4(self) -> None:
        """Test case for get_dataset_v4

        """
        pass

    def test_request_catalog_v4(self) -> None:
        """Test case for request_catalog_v4

        """
        pass


if __name__ == '__main__':
    unittest.main()
