# coding: utf-8

"""
    management-api

    REST API documentation for the management-api

    The version of the OpenAPI document: 4.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.secret_output_v3 import SecretOutputV3

class TestSecretOutputV3(unittest.TestCase):
    """SecretOutputV3 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SecretOutputV3:
        """Test SecretOutputV3
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SecretOutputV3`
        """
        model = SecretOutputV3()
        if include_optional:
            return SecretOutputV3(
                id = '',
                type = 'https://w3id.org/edc/v0.0.1/ns/Secret',
                value = ''
            )
        else:
            return SecretOutputV3(
                value = '',
        )
        """

    def testSecretOutputV3(self):
        """Test SecretOutputV3"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
