# coding: utf-8

"""
    management-api

    REST API documentation for the management-api

    The version of the OpenAPI document: 4.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.atomic_constraint_step import AtomicConstraintStep

class TestAtomicConstraintStep(unittest.TestCase):
    """AtomicConstraintStep unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AtomicConstraintStep:
        """Test AtomicConstraintStep
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AtomicConstraintStep`
        """
        model = AtomicConstraintStep()
        if include_optional:
            return AtomicConstraintStep(
                type = '',
                is_filtered = True,
                filtering_reasons = [
                    ''
                    ],
                function_name = '',
                function_params = [
                    ''
                    ]
            )
        else:
            return AtomicConstraintStep(
                type = '',
        )
        """

    def testAtomicConstraintStep(self):
        """Test AtomicConstraintStep"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
