# coding: utf-8

"""
    management-api

    REST API documentation for the management-api

    The version of the OpenAPI document: 4.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.operator import Operator

class TestOperator(unittest.TestCase):
    """Operator unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOperator(self):
        """Test Operator"""
        # inst = Operator()

if __name__ == '__main__':
    unittest.main()
