# coding: utf-8

"""
    management-api

    REST API documentation for the management-api

    The version of the OpenAPI document: 4.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.contract_definition_v4_api import ContractDefinitionV4Api


class TestContractDefinitionV4Api(unittest.TestCase):
    """ContractDefinitionV4Api unit test stubs"""

    def setUp(self) -> None:
        self.api = ContractDefinitionV4Api()

    def tearDown(self) -> None:
        pass

    def test_create_contract_definition_v4(self) -> None:
        """Test case for create_contract_definition_v4

        """
        pass

    def test_delete_contract_definition_v4(self) -> None:
        """Test case for delete_contract_definition_v4

        """
        pass

    def test_get_contract_definition_v4(self) -> None:
        """Test case for get_contract_definition_v4

        """
        pass

    def test_query_contract_definitions_v4(self) -> None:
        """Test case for query_contract_definitions_v4

        """
        pass

    def test_update_contract_definition_v4(self) -> None:
        """Test case for update_contract_definition_v4

        """
        pass


if __name__ == '__main__':
    unittest.main()
