# coding: utf-8

"""
    management-api

    REST API documentation for the management-api

    The version of the OpenAPI document: 4.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.discovery_v5beta_api import DiscoveryV5betaApi


class TestDiscoveryV5betaApi(unittest.TestCase):
    """DiscoveryV5betaApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DiscoveryV5betaApi()

    def tearDown(self) -> None:
        pass

    def test_discover_v5(self) -> None:
        """Test case for discover_v5

        """
        pass


if __name__ == '__main__':
    unittest.main()
