# coding: utf-8

"""
    management-api

    REST API documentation for the management-api

    The version of the OpenAPI document: 4.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from edc_client.api.dataplane_signaling_registration_v5beta_api import DataplaneSignalingRegistrationV5betaApi


class TestDataplaneSignalingRegistrationV5betaApi(unittest.TestCase):
    """DataplaneSignalingRegistrationV5betaApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DataplaneSignalingRegistrationV5betaApi()

    def tearDown(self) -> None:
        pass

    def test_delete_v5(self) -> None:
        """Test case for delete_v5

        """
        pass

    def test_register_v5(self) -> None:
        """Test case for register_v5

        """
        pass


if __name__ == '__main__':
    unittest.main()
