# coding: utf-8

"""
    management-api

    REST API documentation for the management-api

    The version of the OpenAPI document: 4.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.dataspace_profile import DataspaceProfile

class TestDataspaceProfile(unittest.TestCase):
    """DataspaceProfile unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DataspaceProfile:
        """Test DataspaceProfile
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DataspaceProfile`
        """
        model = DataspaceProfile()
        if include_optional:
            return DataspaceProfile(
                context = [
                    ''
                    ],
                type = '',
                name = '',
                protocol = {"path":"path","namespace":"namespace","binding":"binding","version":"version"},
                json_ld_contexts_url = [
                    ''
                    ]
            )
        else:
            return DataspaceProfile(
                context = [
                    ''
                    ],
                type = '',
                name = '',
                protocol = {"path":"path","namespace":"namespace","binding":"binding","version":"version"},
        )
        """

    def testDataspaceProfile(self):
        """Test DataspaceProfile"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
