# coding: utf-8

"""
    management-api

    REST API documentation for the management-api

    The version of the OpenAPI document: 4.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from edc_client.api.policy_definition_v5beta_api import PolicyDefinitionV5betaApi


class TestPolicyDefinitionV5betaApi(unittest.TestCase):
    """PolicyDefinitionV5betaApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PolicyDefinitionV5betaApi()

    def tearDown(self) -> None:
        pass

    def test_create_execution_plan_v5(self) -> None:
        """Test case for create_execution_plan_v5

        """
        pass

    def test_create_policy_definition_v5(self) -> None:
        """Test case for create_policy_definition_v5

        """
        pass

    def test_delete_policy_definition_v5(self) -> None:
        """Test case for delete_policy_definition_v5

        """
        pass

    def test_get_policy_definition_v5(self) -> None:
        """Test case for get_policy_definition_v5

        """
        pass

    def test_query_policy_definitions_v5(self) -> None:
        """Test case for query_policy_definitions_v5

        """
        pass

    def test_update_policy_definition_v5(self) -> None:
        """Test case for update_policy_definition_v5

        """
        pass

    def test_validate_policy_definition_v5(self) -> None:
        """Test case for validate_policy_definition_v5

        """
        pass


if __name__ == '__main__':
    unittest.main()
