# coding: utf-8

"""
    management-api

    REST API documentation for the management-api

    The version of the OpenAPI document: 4.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from edc_client.models.transfer_process import TransferProcess

class TestTransferProcess(unittest.TestCase):
    """TransferProcess unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TransferProcess:
        """Test TransferProcess
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TransferProcess`
        """
        model = TransferProcess()
        if include_optional:
            return TransferProcess(
                context = [
                    ''
                    ],
                type = '',
                id = '',
                type = 'CONSUMER',
                state = '',
                state_timestamp = 56,
                callback_addresses = [
                    {"authKey":"authKey","@type":"@type","authCodeId":"authCodeId","uri":"uri","transactional":true,"events":["events","events"]}
                    ],
                correlation_id = '',
                asset_id = '',
                contract_id = '',
                transfer_type = '',
                error_detail = '',
                dataplane_metadata = {"@type":"@type","profiles":["profiles","profiles"],"properties":{"key":"value"},"labels":["labels","labels"]}
            )
        else:
            return TransferProcess(
                context = [
                    ''
                    ],
                type = '',
                id = '',
                type = 'CONSUMER',
                state = '',
                state_timestamp = 56,
        )
        """

    def testTransferProcess(self):
        """Test TransferProcess"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
