# coding: utf-8

"""
    management-api

    REST API documentation for the management-api

    The version of the OpenAPI document: 4.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.dataplane_selector_v4_api import DataplaneSelectorV4Api


class TestDataplaneSelectorV4Api(unittest.TestCase):
    """DataplaneSelectorV4Api unit test stubs"""

    def setUp(self) -> None:
        self.api = DataplaneSelectorV4Api()

    def tearDown(self) -> None:
        pass

    def test_get_all_data_plane_instances_v4(self) -> None:
        """Test case for get_all_data_plane_instances_v4

        """
        pass


if __name__ == '__main__':
    unittest.main()
