# coding: utf-8

"""
    management-api

    REST API documentation for the management-api

    The version of the OpenAPI document: 4.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.contract_agreement_v3_api import ContractAgreementV3Api


class TestContractAgreementV3Api(unittest.TestCase):
    """ContractAgreementV3Api unit test stubs"""

    def setUp(self) -> None:
        self.api = ContractAgreementV3Api()

    def tearDown(self) -> None:
        pass

    def test_get_agreement_by_id_v3(self) -> None:
        """Test case for get_agreement_by_id_v3

        """
        pass

    def test_get_negotiation_by_agreement_id_v3(self) -> None:
        """Test case for get_negotiation_by_agreement_id_v3

        """
        pass

    def test_query_agreements_v3(self) -> None:
        """Test case for query_agreements_v3

        """
        pass


if __name__ == '__main__':
    unittest.main()
