# coding: utf-8

"""
    management-api

    REST API documentation for the management-api

    The version of the OpenAPI document: 4.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.asset_v5beta_api import AssetV5betaApi


class TestAssetV5betaApi(unittest.TestCase):
    """AssetV5betaApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AssetV5betaApi()

    def tearDown(self) -> None:
        pass

    def test_create_asset_v5(self) -> None:
        """Test case for create_asset_v5

        """
        pass

    def test_get_asset_v5(self) -> None:
        """Test case for get_asset_v5

        """
        pass

    def test_query_assets_v5(self) -> None:
        """Test case for query_assets_v5

        """
        pass

    def test_remove_asset_v5(self) -> None:
        """Test case for remove_asset_v5

        """
        pass

    def test_update_asset_v5(self) -> None:
        """Test case for update_asset_v5

        """
        pass


if __name__ == '__main__':
    unittest.main()
