# coding: utf-8

"""
    management-api

    REST API documentation for the management-api

    The version of the OpenAPI document: 4.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from edc_client.models.criterion1 import Criterion1

class TestCriterion1(unittest.TestCase):
    """Criterion1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Criterion1:
        """Test Criterion1
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Criterion1`
        """
        model = Criterion1()
        if include_optional:
            return Criterion1(
                context = None,
                type = 'https://w3id.org/edc/v0.0.1/ns/Criterion',
                operand_left = None,
                operand_right = None,
                operator = ''
            )
        else:
            return Criterion1(
                operand_left = None,
                operand_right = None,
                operator = '',
        )
        """

    def testCriterion1(self):
        """Test Criterion1"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
