# coding: utf-8

"""
    management-api

    REST API documentation for the management-api

    The version of the OpenAPI document: 4.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.query_spec import QuerySpec

class TestQuerySpec(unittest.TestCase):
    """QuerySpec unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> QuerySpec:
        """Test QuerySpec
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `QuerySpec`
        """
        model = QuerySpec()
        if include_optional:
            return QuerySpec(
                type = '',
                offset = 0,
                limit = 1,
                sort_field = '',
                sort_order = 'ASC',
                filter_expression = [
                    {"operandRight":"","@type":"@type","operandLeft":"operandLeft","operator":"operator"}
                    ]
            )
        else:
            return QuerySpec(
                type = '',
        )
        """

    def testQuerySpec(self):
        """Test QuerySpec"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
