# coding: utf-8

"""
    management-api

    REST API documentation for the management-api

    The version of the OpenAPI document: 4.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_client.models.data_address import DataAddress
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class AssetInputV3(BaseModel):
    """
    AssetInputV3
    """ # noqa: E501
    context: Dict[str, Any] = Field(alias="@context")
    id: Optional[StrictStr] = Field(default=None, alias="@id")
    type: Optional[StrictStr] = Field(default=None, alias="@type", json_schema_extra={"examples": ["https://w3id.org/edc/v0.0.1/ns/Asset"]})
    data_address: DataAddress = Field(alias="dataAddress")
    private_properties: Optional[Dict[str, Any]] = Field(default=None, alias="privateProperties")
    properties: Dict[str, Any]
    __properties: ClassVar[List[str]] = ["@context", "@id", "@type", "dataAddress", "privateProperties", "properties"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AssetInputV3 from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of data_address
        if self.data_address:
            _dict['dataAddress'] = self.data_address.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AssetInputV3 from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "@context": obj.get("@context"),
            "@id": obj.get("@id"),
            "@type": obj.get("@type"),
            "dataAddress": DataAddress.from_dict(obj["dataAddress"]) if obj.get("dataAddress") is not None else None,
            "privateProperties": obj.get("privateProperties"),
            "properties": obj.get("properties")
        })
        return _obj


