# coding: utf-8

"""
    management-api

    REST API documentation for the management-api

    The version of the OpenAPI document: 4.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_client.models.criterion import Criterion
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ContractDefinitionSchema(BaseModel):
    """
    ContractDefinitionSchema
    """ # noqa: E501
    context: List[StrictStr] = Field(alias="@context")
    type: StrictStr = Field(alias="@type")
    id: Optional[StrictStr] = Field(default=None, alias="@id")
    access_policy_id: StrictStr = Field(alias="accessPolicyId")
    contract_policy_id: StrictStr = Field(alias="contractPolicyId")
    private_properties: Optional[Dict[str, Any]] = Field(default=None, alias="privateProperties")
    assets_selector: Optional[List[Criterion]] = Field(default=None, alias="assetsSelector")
    __properties: ClassVar[List[str]] = ["@context", "@type", "@id", "accessPolicyId", "contractPolicyId", "privateProperties", "assetsSelector"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ContractDefinitionSchema from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in assets_selector (list)
        _items = []
        if self.assets_selector:
            for _item_assets_selector in self.assets_selector:
                if _item_assets_selector:
                    _items.append(_item_assets_selector.to_dict())
            _dict['assetsSelector'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ContractDefinitionSchema from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "@context": obj.get("@context"),
            "@type": obj.get("@type"),
            "@id": obj.get("@id"),
            "accessPolicyId": obj.get("accessPolicyId"),
            "contractPolicyId": obj.get("contractPolicyId"),
            "privateProperties": obj.get("privateProperties"),
            "assetsSelector": [Criterion.from_dict(_item) for _item in obj["assetsSelector"]] if obj.get("assetsSelector") is not None else None
        })
        return _obj


