# coding: utf-8

"""
    management-api

    REST API documentation for the management-api

    The version of the OpenAPI document: 4.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from openapi_client.models.offer import Offer
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class Distribution(BaseModel):
    """
    Distribution
    """ # noqa: E501
    has_policy: Optional[Annotated[List[Optional[Offer]], Field(min_length=1)]] = Field(default=None, alias="hasPolicy")
    access_service: DistributionAccessService = Field(alias="accessService")
    format: StrictStr
    __properties: ClassVar[List[str]] = ["hasPolicy", "accessService", "format"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Distribution from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in has_policy (list)
        _items = []
        if self.has_policy:
            for _item_has_policy in self.has_policy:
                if _item_has_policy:
                    _items.append(_item_has_policy.to_dict())
            _dict['hasPolicy'] = _items
        # override the default output from pydantic by calling `to_dict()` of access_service
        if self.access_service:
            _dict['accessService'] = self.access_service.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Distribution from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "hasPolicy": [Offer.from_dict(_item) for _item in obj["hasPolicy"]] if obj.get("hasPolicy") is not None else None,
            "accessService": DistributionAccessService.from_dict(obj["accessService"]) if obj.get("accessService") is not None else None,
            "format": obj.get("format")
        })
        return _obj

from openapi_client.models.distribution_access_service import DistributionAccessService
# TODO: Rewrite to not use raise_errors
Distribution.model_rebuild(raise_errors=False)

