# coding: utf-8

"""
    management-api

    REST API documentation for the management-api

    The version of the OpenAPI document: 4.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from openapi_client.models.duty import Duty
from openapi_client.models.permission import Permission
from openapi_client.models.policy_class_profile import PolicyClassProfile
from openapi_client.models.prohibition import Prohibition
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class MessageOffer(BaseModel):
    """
    MessageOffer
    """ # noqa: E501
    id: StrictStr = Field(alias="@id")
    profile: Optional[PolicyClassProfile] = None
    permission: Optional[Annotated[List[Permission], Field(min_length=1)]] = None
    prohibition: Optional[Annotated[List[Prohibition], Field(min_length=1)]] = None
    obligation: Optional[Annotated[List[Duty], Field(min_length=1)]] = None
    type: StrictStr = Field(alias="@type")
    target: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["@id", "profile", "permission", "prohibition", "obligation", "@type", "target"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of MessageOffer from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of profile
        if self.profile:
            _dict['profile'] = self.profile.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in permission (list)
        _items = []
        if self.permission:
            for _item_permission in self.permission:
                if _item_permission:
                    _items.append(_item_permission.to_dict())
            _dict['permission'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in prohibition (list)
        _items = []
        if self.prohibition:
            for _item_prohibition in self.prohibition:
                if _item_prohibition:
                    _items.append(_item_prohibition.to_dict())
            _dict['prohibition'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in obligation (list)
        _items = []
        if self.obligation:
            for _item_obligation in self.obligation:
                if _item_obligation:
                    _items.append(_item_obligation.to_dict())
            _dict['obligation'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of MessageOffer from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "@id": obj.get("@id"),
            "profile": PolicyClassProfile.from_dict(obj["profile"]) if obj.get("profile") is not None else None,
            "permission": [Permission.from_dict(_item) for _item in obj["permission"]] if obj.get("permission") is not None else None,
            "prohibition": [Prohibition.from_dict(_item) for _item in obj["prohibition"]] if obj.get("prohibition") is not None else None,
            "obligation": [Duty.from_dict(_item) for _item in obj["obligation"]] if obj.get("obligation") is not None else None,
            "@type": obj.get("@type"),
            "target": obj.get("target")
        })
        return _obj


