# coding: utf-8

"""
    management-api

    REST API documentation for the management-api

    The version of the OpenAPI document: 4.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from edc_client.models.cel_expression_test_request_right_operand import CelExpressionTestRequestRightOperand
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class CelExpressionTestRequest(BaseModel):
    """
    CelExpressionTestRequest
    """ # noqa: E501
    context: List[StrictStr] = Field(alias="@context")
    type: StrictStr = Field(alias="@type")
    expression: StrictStr
    left_operand: StrictStr = Field(alias="leftOperand")
    operator: StrictStr
    right_operand: CelExpressionTestRequestRightOperand = Field(alias="rightOperand")
    params: Optional[Dict[str, Any]] = None
    __properties: ClassVar[List[str]] = ["@context", "@type", "expression", "leftOperand", "operator", "rightOperand", "params"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CelExpressionTestRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of right_operand
        if self.right_operand:
            _dict['rightOperand'] = self.right_operand.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CelExpressionTestRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "@context": obj.get("@context"),
            "@type": obj.get("@type"),
            "expression": obj.get("expression"),
            "leftOperand": obj.get("leftOperand"),
            "operator": obj.get("operator"),
            "rightOperand": CelExpressionTestRequestRightOperand.from_dict(obj["rightOperand"]) if obj.get("rightOperand") is not None else None,
            "params": obj.get("params")
        })
        return _obj


