# coding: utf-8

"""
    management-api

    REST API documentation for the management-api

    The version of the OpenAPI document: 4.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from edc_client.models.callback_address_schema import CallbackAddressSchema
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ContractNegotiationSchema(BaseModel):
    """
    ContractNegotiationSchema
    """ # noqa: E501
    context: List[StrictStr] = Field(alias="@context")
    type: StrictStr = Field(alias="@type")
    id: StrictStr = Field(alias="@id")
    type: StrictStr
    state: StrictStr
    state_timestamp: Optional[StrictInt] = Field(default=None, alias="stateTimestamp")
    protocol: StrictStr
    profile: StrictStr
    created_at: StrictInt = Field(alias="createdAt")
    callback_addresses: Optional[List[CallbackAddressSchema]] = Field(default=None, alias="callbackAddresses")
    counter_party_address: StrictStr = Field(alias="counterPartyAddress")
    counter_party_id: StrictStr = Field(alias="counterPartyId")
    error_detail: Optional[StrictStr] = Field(default=None, alias="errorDetail")
    correlation_id: Optional[StrictStr] = Field(default=None, alias="correlationId")
    asset_id: Optional[StrictStr] = Field(default=None, alias="assetId")
    contract_agreement_id: Optional[StrictStr] = Field(default=None, alias="contractAgreementId")
    __properties: ClassVar[List[str]] = ["@context", "@type", "@id", "type", "state", "stateTimestamp", "protocol", "profile", "createdAt", "callbackAddresses", "counterPartyAddress", "counterPartyId", "errorDetail", "correlationId", "assetId", "contractAgreementId"]

    @field_validator('type')
    def type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['CONSUMER', 'PROVIDER']):
            raise ValueError("must be one of enum values ('CONSUMER', 'PROVIDER')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ContractNegotiationSchema from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in callback_addresses (list)
        _items = []
        if self.callback_addresses:
            for _item_callback_addresses in self.callback_addresses:
                if _item_callback_addresses:
                    _items.append(_item_callback_addresses.to_dict())
            _dict['callbackAddresses'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ContractNegotiationSchema from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "@context": obj.get("@context"),
            "@type": obj.get("@type"),
            "@id": obj.get("@id"),
            "type": obj.get("type"),
            "state": obj.get("state"),
            "stateTimestamp": obj.get("stateTimestamp"),
            "protocol": obj.get("protocol"),
            "profile": obj.get("profile"),
            "createdAt": obj.get("createdAt"),
            "callbackAddresses": [CallbackAddressSchema.from_dict(_item) for _item in obj["callbackAddresses"]] if obj.get("callbackAddresses") is not None else None,
            "counterPartyAddress": obj.get("counterPartyAddress"),
            "counterPartyId": obj.get("counterPartyId"),
            "errorDetail": obj.get("errorDetail"),
            "correlationId": obj.get("correlationId"),
            "assetId": obj.get("assetId"),
            "contractAgreementId": obj.get("contractAgreementId")
        })
        return _obj


