# coding: utf-8

"""
    management-api

    REST API documentation for the management-api

    The version of the OpenAPI document: 4.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from edc_client.models.constraint_step import ConstraintStep
from edc_client.models.duty_step import DutyStep
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class PermissionStep(BaseModel):
    """
    PermissionStep
    """ # noqa: E501
    is_filtered: Optional[StrictBool] = Field(default=None, alias="isFiltered")
    filtering_reasons: Optional[List[StrictStr]] = Field(default=None, alias="filteringReasons")
    constraint_steps: Optional[List[ConstraintStep]] = Field(default=None, alias="constraintSteps")
    rule_functions: Optional[List[StrictStr]] = Field(default=None, alias="ruleFunctions")
    type: StrictStr = Field(alias="@type")
    duty_steps: Optional[List[DutyStep]] = Field(default=None, alias="dutySteps")
    __properties: ClassVar[List[str]] = ["isFiltered", "filteringReasons", "constraintSteps", "ruleFunctions", "@type", "dutySteps"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PermissionStep from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in constraint_steps (list)
        _items = []
        if self.constraint_steps:
            for _item_constraint_steps in self.constraint_steps:
                if _item_constraint_steps:
                    _items.append(_item_constraint_steps.to_dict())
            _dict['constraintSteps'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in duty_steps (list)
        _items = []
        if self.duty_steps:
            for _item_duty_steps in self.duty_steps:
                if _item_duty_steps:
                    _items.append(_item_duty_steps.to_dict())
            _dict['dutySteps'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PermissionStep from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "isFiltered": obj.get("isFiltered"),
            "filteringReasons": obj.get("filteringReasons"),
            "constraintSteps": [ConstraintStep.from_dict(_item) for _item in obj["constraintSteps"]] if obj.get("constraintSteps") is not None else None,
            "ruleFunctions": obj.get("ruleFunctions"),
            "@type": obj.get("@type"),
            "dutySteps": [DutyStep.from_dict(_item) for _item in obj["dutySteps"]] if obj.get("dutySteps") is not None else None
        })
        return _obj


