# coding: utf-8

"""
    management-api

    REST API documentation for the management-api

    The version of the OpenAPI document: 4.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from edc_client.models.callback_address1 import CallbackAddress1
from edc_client.models.data_address import DataAddress
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class TransferProcessV3(BaseModel):
    """
    TransferProcessV3
    """ # noqa: E501
    id: Optional[StrictStr] = Field(default=None, alias="@id")
    type: Optional[StrictStr] = Field(default=None, alias="@type", json_schema_extra={"examples": ["https://w3id.org/edc/v0.0.1/ns/TransferProcess"]})
    callback_addresses: Optional[List[CallbackAddress1]] = Field(default=None, alias="callbackAddresses")
    contract_agreement_id: Optional[StrictStr] = Field(default=None, alias="contractAgreementId")
    counter_party_address: Optional[StrictStr] = Field(default=None, alias="counterPartyAddress")
    counter_party_id: Optional[StrictStr] = Field(default=None, alias="counterPartyId")
    data_destination: Optional[DataAddress] = Field(default=None, alias="dataDestination")
    error_detail: Optional[StrictStr] = Field(default=None, alias="errorDetail")
    private_properties: Optional[Dict[str, Any]] = Field(default=None, alias="privateProperties")
    protocol: Optional[StrictStr] = None
    state: Optional[StrictStr] = None
    type: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["@id", "@type", "callbackAddresses", "contractAgreementId", "counterPartyAddress", "counterPartyId", "dataDestination", "errorDetail", "privateProperties", "protocol", "state", "type"]

    @field_validator('type')
    def type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['CONSUMER', 'PROVIDER']):
            raise ValueError("must be one of enum values ('CONSUMER', 'PROVIDER')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TransferProcessV3 from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in callback_addresses (list)
        _items = []
        if self.callback_addresses:
            for _item_callback_addresses in self.callback_addresses:
                if _item_callback_addresses:
                    _items.append(_item_callback_addresses.to_dict())
            _dict['callbackAddresses'] = _items
        # override the default output from pydantic by calling `to_dict()` of data_destination
        if self.data_destination:
            _dict['dataDestination'] = self.data_destination.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TransferProcessV3 from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "@id": obj.get("@id"),
            "@type": obj.get("@type"),
            "callbackAddresses": [CallbackAddress1.from_dict(_item) for _item in obj["callbackAddresses"]] if obj.get("callbackAddresses") is not None else None,
            "contractAgreementId": obj.get("contractAgreementId"),
            "counterPartyAddress": obj.get("counterPartyAddress"),
            "counterPartyId": obj.get("counterPartyId"),
            "dataDestination": DataAddress.from_dict(obj["dataDestination"]) if obj.get("dataDestination") is not None else None,
            "errorDetail": obj.get("errorDetail"),
            "privateProperties": obj.get("privateProperties"),
            "protocol": obj.get("protocol"),
            "state": obj.get("state"),
            "type": obj.get("type")
        })
        return _obj


